name: Deploy React Application

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

# Jobs to run in the workflow
jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (specify the version you need for the app)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the appropriate Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the React application
      - name: Build the app
        run: npm run build

      # Step 5: Deploy the app (example for deploying to GitHub Pages)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch where you want to deploy the app
          folder: build     # The folder to deploy (usually the build folder in React)

      # Step 6: Notify success
      - name: Notify success
        run: echo "Deployment successful!"

